version: "3.3"
services:
  api:
    image: "ghcr.io/packetframe/api:${PFDEV_TAG}"
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - METRICS_LISTEN=:8081

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=api
