name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - run: go generate -x
      - run: go build -v .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Start postgres container
        run: docker run --rm -e POSTGRES_PASSWORD=api -e POSTGRES_USER=api -e POSTGRES_DB=api -p 5432:5432 -d postgres && sleep 2

      - name: go test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Stop Postgres container
        run: docker kill $(docker ps -aq)
